### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by MickL** [oculus42/short-uuid#40]
When using the module with `.generate()`:

>  DeprecationWarning: Deep requiring like `const uuidv4 = require('uuid/v4');` is deprecated as of uuid@7.x. Please require the top-level module when using the Node.js CommonJS module or use ECMAScript Modules when bundling for the browser. See https://github.com/uuidjs/uuid#deep-requires-now-deprecated for more information.

**Comment by oculus42** [comment]
There won't be a new release for this update for a bit, even with #44, because the newer version of uuid is not written in ES5.1, so it will require some new tooling to continue to provide a browser-compatible version.

I might consider dropping the browser export and pushing a new major release to allow NodeJS users to move forward.

**Comment by oculus42** [comment]
v4.0.1 is released, written in ES6, with uuid@8.3.0.
